apiVersion: v1
kind: ConfigMap
metadata:
  name: video-app-config
  namespace: video-processor
data:
  LOG_LEVEL: "INFO"
  PYTHONUNBUFFERED: "1"
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres123@postgres-video:5432/video_db"
  REDIS_URL: "redis://redis:6379/1"
  AWS_ENDPOINT_URL: "http://localstack:4566"
  AWS_DEFAULT_REGION: "us-east-1"
  S3_BUCKET: "video-uploads"
  SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:000000000000:video-events"
  AUTH_SERVICE_URL: "http://auth-service:8000"
